# Generated by Django 2.0.6 on 2018-06-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0002_auto_20180625_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricola',
            field=models.CharField(blank=True, help_text='come rappresentata su CSA', max_length=254, null=True, verbose_name='Matricola'),
        ),
    ]
