"""
Django settings for django_saml2_idp project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lrx(fg&+2e=$l=y8$!+l68_=-lm3*n+myg%r3z!yjm(lg*l%-z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'djangosaml2idp',
    'idp',
    'ldap_peoples',
    'rangefilter'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_saml2_idp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_saml2_idp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangosaml2idp',
        'HOST': 'localhost',
        'USER': 'django-saml2-idp',
        'PASSWORD': 'django-saml2-idp78',
        'PORT': ''
    }
}

if 'ldap_peoples' in INSTALLED_APPS:
    import ldap
    LDAP_BASE_DOMAIN = 'testunical.it'
    from ldap_peoples.settings import *
    LDAP_OU = 'people'
    LDAP_BASEDN = 'dc='+',dc='.join(LDAP_BASE_DOMAIN.split('.'))
    LDAP_CONNECTION_OPTIONS = {ldap.OPT_PROTOCOL_VERSION: 3,
                               ldap.OPT_DEBUG_LEVEL: 255,
                               # ldap.OPT_X_TLS_CACERTFILE: LDAP_CACERT,

                               # force /etc/ldap.conf configuration.
                               # ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_NEVER,
                               # ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_DEMAND,
                               # ldap.OPT_X_TLS: ldap.OPT_X_TLS_DEMAND,
                               # ldap.OPT_X_TLS_DEMAND: True,
                               # ldap.OPT_X_TLS: ldap.OPT_X_TLS_NEVER,
                               # ldap.OPT_X_TLS_DEMAND: False,
                              }

    DATABASES['ldap'] = {
        'ENGINE': 'ldapdb.backends.ldap',
        # only in localhost
        #'NAME': 'ldapi:///',
        'NAME': 'ldapi://',
        # 'NAME': 'ldaps://127.0.0.1/',
        'USER': 'cn=admin,{}'.format(LDAP_BASEDN),
        'PASSWORD': 'slapdsecret',
        # 'PORT': 636,
        #'TLS': True,
        'RETRY_DELAY': 8,
        'RETRY_MAX': 3,
        'CONNECTION_OPTIONS': LDAP_CONNECTION_OPTIONS
     }
    DATABASE_ROUTERS = ['ldapdb.router.Router']

AUTHENTICATION_BACKENDS = [
                            'idp.ldap_auth.LdapAcademiaAuthBackend',
                            'django.contrib.auth.backends.ModelBackend',
                            # FIX TODO in Django 2.1
                            # 'unical_ict.auth.SessionUniqueBackend',
                          ]

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_ROOT = STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

if 'djangosaml2idp' in INSTALLED_APPS:
    from . idp_pysaml2 import *

    # pySAML2 IDP
    SESSION_EXPIRE_AT_BROWSER_CLOSE=True
    SESSION_COOKIE_AGE = 60 * 60 # an hour

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'filters': {
            'require_debug_false': {
                '()': 'django.utils.log.RequireDebugFalse'
            }
        },
        'handlers': {
            'mail_admins': {
                'level': 'ERROR',
                'filters': ['require_debug_false'],
                'class': 'django.utils.log.AdminEmailHandler'
            },
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django.request': {
                'handlers': ['mail_admins'],
                'level': 'ERROR',
                'propagate': True,
            },
            'djangosaml2idp': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        }
    }
